@startuml
class ZeroEvenOdd{
    -int n;
    -int counter;
    -std::condition_variable cv
    -std::mutex m;
    -bool generate0;
    -bool done;
    -void incCounter();
    -void togglegenerate0();
    +ZeroOddEven(int n);
    +void odd(std::function<void(std::string&, int)>);
    +void even(std::function<void(std::string&, int)>);
    +void zero(std::function<void(std::string&, int)>);
}
@enduml